/* @generated by scripts/generate-contracts.mjs from 39 versioned JSON Schemas. */
export const CONTRACT_SCHEMA_VERSION = "1.0.0" as const;

export type ViewState =
  | "LOADING"
  | "READY"
  | "EMPTY"
  | "PARTIAL"
  | "STALE"
  | "VALIDATING"
  | "EXECUTING"
  | "REQUIRES_CONFIRMATION"
  | "ERROR"
  | "INCOMPATIBLE_SCHEMA"
  | "LOCKED";

export interface Envelope<T> {
  schema_version: typeof CONTRACT_SCHEMA_VERSION;
  state: ViewState;
  projection_sequence: number;
  event_store_sequence: number;
  projection_version?: string;
  freshness_status?: "CURRENT" | "STALE" | "INVALID";
  generated_at?: string;
  data: T;
}

export interface CapabilityManifest {
  extension_version: string;
  product_version?: string;
  contract_version?: string;
  store_schema_version?: number;
  ui_contract_version?: string;
  schema_version: string;
  capabilities: Record<string, boolean>;
  projection_versions?: Record<string, string>;
}

export type PeriodMode = "MONTH" | "YEAR" | "CUSTOM_RANGE";
export type PeriodAggregation = "DAY" | "WEEK" | "MONTH";
export interface PeriodSelection {
  mode: PeriodMode;
  start_date: string;
  end_date: string;
  timezone?: string;
  display_label: string;
  aggregation: PeriodAggregation;
  comparison_period?: Record<string, unknown> | null;
}

export interface AvailablePeriods {
  earliest_date: string;
  latest_date: string;
  available_months: string[];
  available_years: number[];
  max_custom_range_days: number;
  supported_modes: string[];
  reserved_modes: string[];
}

export type AccountOverviewStatus =
  | "MATCHED" | "DIFFERENCE" | "STALE" | "MISSING_BALANCE" | "REVIEW_REQUIRED" | "CLOSED";

export interface AccountOverviewRow {
  account_id: string;
  display_name: string;
  account_type: string;
  institution: string;
  currency: string;
  status: string;
  reported_balance: string | null;
  reported_balance_date: string | null;
  calculated_balance: string | null;
  calculated_balance_date: string | null;
  balance_difference: string | null;
  reconciliation_status: string;
  period_income: string;
  period_expenses: string;
  period_net_cashflow: string;
  last_import_month: string | null;
  last_import_status: string | null;
  open_review_count: number;
  data_freshness: "CURRENT" | "STALE";
  position_count: number | null;
  acquisition_value: string | null;
  open_investment_funding_relations: number;
  overview_status: AccountOverviewStatus;
}

export interface AccountOverviewList {
  period: PeriodSelection;
  accounts: AccountOverviewRow[];
}

export interface AccountBalanceLedgerRow {
  balance_type: "OPENING" | "CLOSING" | "INTERMEDIATE" | "CALCULATED";
  balance_date: string | null;
  reported_value: string | null;
  calculated_value: string | null;
  currency: string;
  source: string;
  confirmation_status: string;
  correction_status: string;
  adjustment_reason: string | null;
  carry_forward_source_reconciliation_id: string | null;
  sequence_number: number;
}

export interface AccountPeriodSummary {
  account_id: string;
  period: PeriodSelection;
  period_income: string;
  period_expenses: string;
  period_net_cashflow: string;
  transaction_count: number;
  balance_point_count: number;
}

export interface AccountDetailWorkspace {
  account: AccountOverviewRow;
  overview_status: AccountOverviewStatus;
  period: PeriodSelection;
  period_summary: AccountPeriodSummary;
  balance_history: AccountBalanceLedgerRow[];
  reconciliation: Record<string, unknown> | null;
  open_review_count: number;
}

export interface AccountTransactionRow {
  transaction_id: string;
  account_id: string;
  booking_date: string;
  value_date?: string;
  amount: string;
  currency: string;
  direction: "CREDIT" | "DEBIT";
  counterparty: string;
  normalized_description?: string;
  category_code?: string;
  duplicate_status?: string;
  transfer_status?: string;
  refund_status?: string;
  investment_funding_status?: string;
  export_id?: string;
  section_id?: string;
}

export interface AccountTransactionList {
  account_id: string;
  period: PeriodSelection | null;
  transactions: AccountTransactionRow[];
}

export interface AccountReconciliationRow {
  reconciliation_id: string;
  account_id: string;
  report_month: string;
  period_start: string;
  period_end: string;
  opening_balance: string | null;
  relevant_transaction_count: number;
  calculated_closing_balance: string | null;
  reported_closing_balance: string | null;
  balance_difference: string | null;
  status: "MATCHED" | "DIFFERENCE" | "REVIEW_REQUIRED" | "MISSING_OPENING_BALANCE" | "NO_REPORTED_CLOSING_BALANCE";
  raw_status: string;
  explanation: string | null;
  export_id: string;
}

export interface AccountReconciliationList {
  account_id: string;
  reconciliations: AccountReconciliationRow[];
}

export interface AccountImportRow {
  export_id: string;
  section_id: string;
  section_type: string;
  bank_identifier: string | null;
  report_month: string;
  period_start: string;
  period_end: string;
  import_status: string;
  record_count: number;
  parser_version: string;
  profile_version: string;
  content_hash: string;
  imported_at: string;
}

export interface AccountImportList {
  account_id: string;
  imports: AccountImportRow[];
}

export interface AccountPositionRow {
  position_id: string;
  account_id: string;
  security_identifier_type: string;
  security_identifier: string;
  security_name: string;
  opening_quantity: string;
  purchased_quantity: string;
  sold_quantity: string;
  closing_quantity: string;
  reported_closing_quantity: string | null;
  position_difference: string | null;
  market_value: string | null;
  acquisition_value: string | null;
  currency: string | null;
}

export interface AccountPositionList {
  account_id: string;
  positions: AccountPositionRow[];
}

export interface AccountAuditEvent {
  sequence_number: number;
  event_id: string;
  event_type: string;
  occurred_at: string;
  aggregate_type: string;
  aggregate_id: string;
  account_id: string;
  related_import_id: string | null;
  related_balance_id: string | null;
  payload: Record<string, unknown>;
}

export interface AccountAuditTrail {
  account_id: string;
  period: PeriodSelection | null;
  audit_history: AccountAuditEvent[];
}

export interface ImportHistoryRecord {
  export_id: string;
  bank_identifier: string;
  report_month: string;
  imported_at: string;
  section_count: number;
  completed_section_count: number;
  status: string;
  import_profile: string;
  parser_version: string;
  source_file_hash: string;
  resumable: boolean;
}

export interface ImportWizardState {
  export_id: string;
  current_step: 1 | 2 | 3 | 4 | 5;
  completed_steps: number[];
  status: string;
  can_resume: boolean;
  continuation_allowed: boolean;
  requires_preview_confirmation: boolean;
  analysis: Record<string, unknown>;
  requirements: Array<Record<string, unknown>>;
  execution_result: Record<string, unknown> | null;
}

export interface ImportExecutionResult {
  export_id: string;
  status: string;
  bank_identifier: string;
  report_month: string;
  raw_transaction_count: number;
  normalized_transaction_count: number;
  security_transaction_count: number;
  section_results: Array<Record<string, unknown>>;
  relations: Array<Record<string, unknown>>;
  balance_reconciliations: Array<Record<string, unknown>>;
  position_reconciliations: Array<Record<string, unknown>>;
}

export type StartupState =
  | "READY" | "WORKSPACE_LOCKED" | "KEYCHAIN_UNAVAILABLE" | "STORE_CORRUPTED"
  | "MIGRATION_REQUIRED" | "MIGRATION_FAILED" | "BACKUP_REQUIRED"
  | "INCOMPATIBLE_VERSION" | "BUNDLE_TAMPERED" | "INSUFFICIENT_SPACE";
export interface StartupStatus {
  status: StartupState;
  error_code: string | null;
  checks: Record<string, string>;
  read_only_diagnostics_available: true;
  recovery_document: "RECOVERY.md";
}

export type SecurityCheck = "PASSED" | "FAILED" | "NOT_CHECKED";
export interface RuntimeSecurityStatus {
  extension_version: string;
  schema_version: string;
  checks: Record<string, SecurityCheck>;
  last_event_sequence: number;
}

export interface Dashboard {
  month: string;
  effective_income: string;
  effective_expenses: string;
  net_cashflow: string;
  expected_month_end_surplus: string | null;
  remaining_expected_income: string;
  remaining_expected_expenses: string;
  savings_rate: string | null;
  open_reviews: number;
  liquid_balance?: string;
  liquid_balance_as_of?: string;
  projected_month_end_balance?: string | null;
  net_worth?: string;
  net_worth_as_of?: string;
}

export interface Account {
  account_id: string;
  display_name: string;
  account_type: string;
  institution: string;
  currency: string;
  status: string;
  include_in_cashflow: boolean;
  include_in_liquidity: boolean;
  include_in_net_worth: boolean;
  opened_at: string;
  closed_at: string | null;
  masked_reference: string | null;
  latest_balance: string | null;
  available_balance: string | null;
  balance_date: string | null;
  balance_source: string | null;
  reconciliation_status: string;
  freshness: "CURRENT" | "STALE";
}

export interface LiquidityOverview {
  valuation_currency: string;
  as_of: string;
  liquid_funds: string;
  accounts: Account[];
  stale_account_ids: string[];
  currency_conflicts: string[];
}

export interface NetWorthOverview {
  valuation_currency: string;
  as_of: string;
  liquid_funds: string;
  savings: string;
  investments: string;
  other_assets: string;
  total_assets: string;
  liabilities: string;
  net_worth: string;
  investable_assets: string;
  currency_conflicts: string[];
  source_snapshot_ids: string[];
}

export interface BackupRecord {
  archive_id: string | null;
  path: string;
  size: number;
  created_at?: string;
  event_store_sequence?: number;
  verification_status: "VALID" | "INVALID";
  error_code?: string;
}

export interface StoreIntegrity {
  status: "VALID" | "INVALID";
  checked_at: string;
  store_schema_version?: number;
  event_count?: number;
  last_event_sequence?: number;
  import_file_count?: number;
  storage_encryption?: "FERNET_AUTHENTICATED";
  error_code?: string;
}

export interface EncryptionKeyStatus {
  strategy: string;
  status: "AVAILABLE" | "NOT_PROVISIONED";
  fingerprint: string | null;
  independent_from_store?: boolean | null;
}

export interface KeyStatus {
  database_key: EncryptionKeyStatus;
  archive_key: EncryptionKeyStatus;
}

export interface MigrationStatus {
  current_store_schema_version: number;
  supported_store_schema_version: number;
  status: "CURRENT" | "MIGRATION_REQUIRED" | "DOWNGRADE_BLOCKED";
  history: Array<Record<string, unknown>>;
  downgrade_protection: "ENABLED";
}

export interface Transaction {
  transaction_id: string;
  booking_date: string;
  amount: string;
  currency: string;
  counterparty: string;
  description?: string;
  normalized_description?: string;
  category_code: string;
  duplicate_status?: string;
  transfer_status?: string;
  refund_status?: string;
  cashflow_relevant?: boolean;
}

export interface ForecastScenario {
  forecast_id: string;
  scenario: string;
  predicted_surplus: string;
  expected_income: string;
  expected_fixed_expenses: string;
  predicted_variable_expenses: string;
  lower_bound: string;
  upper_bound: string;
  confidence: string;
  source_event_sequence: number;
  forecast_policy_version: string;
  status: string;
}

export interface RecurringPattern {
  pattern_id: string;
  merchant_key: string;
  frequency: string;
  expected_amount: string;
  category_code?: string;
  direction?: string;
  status: string;
  confidence: string;
  expected_day_from?: number;
  expected_day_to?: number;
}

export interface ExpectedTransaction {
  expected_transaction_id: string;
  recurring_pattern_id: string;
  expected_date: string;
  expected_amount: string;
  direction: string;
  status: string;
}
