/* @generated by scripts/generate-contracts.mjs from 23 versioned JSON Schemas. */
export const CONTRACT_SCHEMA_VERSION = "1.0.0" as const;

export type ViewState =
  | "LOADING"
  | "READY"
  | "EMPTY"
  | "PARTIAL"
  | "STALE"
  | "ERROR"
  | "INCOMPATIBLE_SCHEMA"
  | "LOCKED";

export interface Envelope<T> {
  schema_version: typeof CONTRACT_SCHEMA_VERSION;
  state: ViewState;
  projection_sequence: number;
  event_store_sequence: number;
  data: T;
}

export interface CapabilityManifest {
  extension_version: string;
  schema_version: string;
  capabilities: Record<string, boolean>;
}

export type SecurityCheck = "PASSED" | "FAILED" | "NOT_CHECKED";
export interface RuntimeSecurityStatus {
  extension_version: string;
  schema_version: string;
  checks: Record<string, SecurityCheck>;
  last_event_sequence: number;
}

export interface Dashboard {
  month: string;
  effective_income: string;
  effective_expenses: string;
  net_cashflow: string;
  expected_month_end_surplus: string | null;
  remaining_expected_income: string;
  remaining_expected_expenses: string;
  savings_rate: string | null;
  open_reviews: number;
  liquid_balance?: string;
  liquid_balance_as_of?: string;
  projected_month_end_balance?: string | null;
  net_worth?: string;
  net_worth_as_of?: string;
}

export interface Account {
  account_id: string;
  display_name: string;
  account_type: string;
  institution: string;
  currency: string;
  status: string;
  include_in_cashflow: boolean;
  include_in_liquidity: boolean;
  include_in_net_worth: boolean;
  opened_at: string;
  closed_at: string | null;
  masked_reference: string | null;
  latest_balance: string | null;
  available_balance: string | null;
  balance_date: string | null;
  balance_source: string | null;
  reconciliation_status: string;
  freshness: "CURRENT" | "STALE";
}

export interface LiquidityOverview {
  valuation_currency: string;
  as_of: string;
  liquid_funds: string;
  accounts: Account[];
  stale_account_ids: string[];
  currency_conflicts: string[];
}

export interface NetWorthOverview {
  valuation_currency: string;
  as_of: string;
  liquid_funds: string;
  savings: string;
  investments: string;
  other_assets: string;
  total_assets: string;
  liabilities: string;
  net_worth: string;
  investable_assets: string;
  currency_conflicts: string[];
  source_snapshot_ids: string[];
}

export interface BackupRecord {
  archive_id: string | null;
  path: string;
  size: number;
  created_at?: string;
  event_store_sequence?: number;
  verification_status: "VALID" | "INVALID";
  error_code?: string;
}

export interface StoreIntegrity {
  status: "VALID" | "INVALID";
  checked_at: string;
  store_schema_version?: number;
  event_count?: number;
  last_event_sequence?: number;
  import_file_count?: number;
  storage_encryption?: "FERNET_AUTHENTICATED";
  error_code?: string;
}

export interface EncryptionKeyStatus {
  strategy: string;
  status: "AVAILABLE" | "NOT_PROVISIONED";
  fingerprint: string | null;
  independent_from_store?: boolean | null;
}

export interface KeyStatus {
  database_key: EncryptionKeyStatus;
  archive_key: EncryptionKeyStatus;
}

export interface MigrationStatus {
  current_store_schema_version: number;
  supported_store_schema_version: number;
  status: "CURRENT" | "MIGRATION_REQUIRED" | "DOWNGRADE_BLOCKED";
  history: Array<Record<string, unknown>>;
  downgrade_protection: "ENABLED";
}

export interface Transaction {
  transaction_id: string;
  booking_date: string;
  amount: string;
  currency: string;
  counterparty: string;
  description?: string;
  normalized_description?: string;
  category_code: string;
  duplicate_status?: string;
  transfer_status?: string;
  refund_status?: string;
  cashflow_relevant?: boolean;
}

export interface ForecastScenario {
  forecast_id: string;
  scenario: string;
  predicted_surplus: string;
  expected_income: string;
  expected_fixed_expenses: string;
  predicted_variable_expenses: string;
  lower_bound: string;
  upper_bound: string;
  confidence: string;
  source_event_sequence: number;
  forecast_policy_version: string;
  status: string;
}

export interface RecurringPattern {
  pattern_id: string;
  merchant_key: string;
  frequency: string;
  expected_amount: string;
  category_code?: string;
  direction?: string;
  status: string;
  confidence: string;
  expected_day_from?: number;
  expected_day_to?: number;
}

export interface ExpectedTransaction {
  expected_transaction_id: string;
  recurring_pattern_id: string;
  expected_date: string;
  expected_amount: string;
  direction: string;
  status: string;
}
