/* @generated by scripts/generate-contracts.mjs from 9 versioned JSON Schemas. */
export const CONTRACT_SCHEMA_VERSION = "1.0.0" as const;

export type ViewState =
  | "LOADING"
  | "READY"
  | "EMPTY"
  | "PARTIAL"
  | "STALE"
  | "ERROR"
  | "INCOMPATIBLE_SCHEMA"
  | "LOCKED";

export interface Envelope<T> {
  schema_version: typeof CONTRACT_SCHEMA_VERSION;
  state: ViewState;
  projection_sequence: number;
  event_store_sequence: number;
  data: T;
}

export interface CapabilityManifest {
  extension_version: string;
  schema_version: string;
  capabilities: Record<string, boolean>;
}

export type SecurityCheck = "PASSED" | "FAILED" | "NOT_CHECKED";
export interface RuntimeSecurityStatus {
  extension_version: string;
  schema_version: string;
  checks: Record<string, SecurityCheck>;
  last_event_sequence: number;
}

export interface Dashboard {
  month: string;
  effective_income: string;
  effective_expenses: string;
  net_cashflow: string;
  expected_month_end_surplus: string | null;
  remaining_expected_income: string;
  remaining_expected_expenses: string;
  savings_rate: string | null;
  open_reviews: number;
}

export interface Transaction {
  transaction_id: string;
  booking_date: string;
  amount: string;
  currency: string;
  counterparty: string;
  description?: string;
  normalized_description?: string;
  category_code: string;
  duplicate_status?: string;
  transfer_status?: string;
  refund_status?: string;
  cashflow_relevant?: boolean;
}

export interface ForecastScenario {
  forecast_id: string;
  scenario: string;
  predicted_surplus: string;
  expected_income: string;
  expected_fixed_expenses: string;
  predicted_variable_expenses: string;
  lower_bound: string;
  upper_bound: string;
  confidence: string;
  source_event_sequence: number;
  forecast_policy_version: string;
  status: string;
}

export interface RecurringPattern {
  pattern_id: string;
  merchant_key: string;
  frequency: string;
  expected_amount: string;
  category_code?: string;
  direction?: string;
  status: string;
  confidence: string;
  expected_day_from?: number;
  expected_day_to?: number;
}

export interface ExpectedTransaction {
  expected_transaction_id: string;
  recurring_pattern_id: string;
  expected_date: string;
  expected_amount: string;
  direction: string;
  status: string;
}
