import type { Envelope } from "./contracts/generated";

const envelope = <T>(data: T, state: Envelope<T>["state"] = "READY"): Envelope<T> => ({
  schema_version: "1.0.0",
  state,
  projection_sequence: 892,
  event_store_sequence: 892,
  data,
});

export function mockQuery(name: string, payload: Record<string, unknown> = {}): Envelope<unknown> {
  const month = String(payload.month ?? "2026-07");
  const responses: Record<string, Envelope<unknown>> = {
    GetCapabilityManifest: envelope({
      extension_version: "1.2.0",
      contract_version: "1.3.0",
      store_schema_version: 3,
      schema_version: "1.0.0",
      capabilities: {
        imports: true,
        import_capability: true,
        multi_account_import_capability: true,
        balance_reconciliation_capability: true,
        position_reconciliation_capability: true,
        investment_funding_capability: true,
        classification: true,
        reconciliation: true,
        recurring_patterns: true,
        forecasting: true,
        forecast_evaluation: true,
        accounts: true,
        balances: true,
        liquidity: true,
        net_worth: true,
        wealth: true,
        backup: true,
        restore: true,
        data_export: true,
        migrations: true,
        tax: false,
        receipts: false,
        cloud_sync: false,
        external_models: false,
      },
    }),
    GetStartupStatus: envelope({
      status: "READY",
      error_code: null,
      checks: { workspace_lock: "LOCKED", key: "AVAILABLE", store_integrity: "VALID", migration: "CURRENT", free_space: "SUFFICIENT", bundle_integrity: "VALID" },
      read_only_diagnostics_available: true,
      recovery_document: "RECOVERY.md",
    }),
    GetRuntimeSecurityStatus: envelope({
      extension_version: "1.2.0",
      schema_version: "1.0.0",
      last_event_sequence: 892,
      checks: {
        data_path_local: "PASSED",
        git_path_protection: "PASSED",
        cloud_sync_check: "PASSED",
        keychain_available: "NOT_CHECKED",
        snapshot_loaded: "PASSED",
        snapshot_integrity: "PASSED",
        network_egress_disabled: "PASSED",
        schema_compatibility: "PASSED",
      },
    }),
    GetDashboard: envelope({
      month,
      effective_income: "4320.00",
      effective_expenses: "2598.40",
      net_cashflow: "1721.60",
      expected_month_end_surplus: "1438.20",
      remaining_expected_income: "320.00",
      remaining_expected_expenses: "603.40",
      savings_rate: "39.85",
      open_reviews: 7,
      liquid_balance: "18420.00",
      liquid_balance_as_of: "2026-07-20",
      projected_month_end_balance: "18136.60",
      net_worth: "86420.00",
      net_worth_as_of: "2026-07-20",
    }),
    ListAccounts: envelope({ accounts: [
      { account_id: "acc_main", display_name: "Girokonto", account_type: "CHECKING", institution: "Lokale Bank", currency: "EUR", status: "ACTIVE", include_in_cashflow: true, include_in_liquidity: true, include_in_net_worth: true, opened_at: "2022-03-01", closed_at: null, masked_reference: "•••• 4821", latest_balance: "6420.00", available_balance: "6180.00", balance_date: "2026-07-20", balance_source: "IMPORT_SOURCE", reconciliation_status: "MATCHED", freshness: "CURRENT" },
      { account_id: "acc_savings", display_name: "Rücklage", account_type: "SAVINGS", institution: "Lokale Bank", currency: "EUR", status: "ACTIVE", include_in_cashflow: false, include_in_liquidity: true, include_in_net_worth: true, opened_at: "2021-01-01", closed_at: null, masked_reference: "•••• 1288", latest_balance: "12000.00", available_balance: "12000.00", balance_date: "2026-07-18", balance_source: "MANUAL_ENTRY", reconciliation_status: "NOT_RECONCILED", freshness: "CURRENT" },
      { account_id: "acc_depot", display_name: "Wertpapierdepot", account_type: "BROKERAGE", institution: "Direktbank", currency: "EUR", status: "ACTIVE", include_in_cashflow: false, include_in_liquidity: false, include_in_net_worth: true, opened_at: "2020-05-01", closed_at: null, masked_reference: "•••• 7704", latest_balance: "72500.00", available_balance: null, balance_date: "2026-07-01", balance_source: "MANUAL_ENTRY", reconciliation_status: "NOT_RECONCILED", freshness: "CURRENT" },
      { account_id: "acc_card", display_name: "Kreditkarte", account_type: "CREDIT_CARD", institution: "Kartenbank", currency: "EUR", status: "ACTIVE", include_in_cashflow: true, include_in_liquidity: false, include_in_net_worth: true, opened_at: "2023-06-01", closed_at: null, masked_reference: "•••• 9012", latest_balance: "-2480.00", available_balance: null, balance_date: "2026-05-31", balance_source: "IMPORT_SOURCE", reconciliation_status: "REVIEW_REQUIRED", freshness: "STALE" },
    ] }, "STALE"),
    GetAccount: envelope({ account: { account_id: String(payload.account_id ?? "acc_main"), display_name: payload.account_id === "acc_card" ? "Kreditkarte" : "Girokonto", account_type: payload.account_id === "acc_card" ? "CREDIT_CARD" : "CHECKING", institution: payload.account_id === "acc_card" ? "Kartenbank" : "Lokale Bank", currency: "EUR", status: "ACTIVE", include_in_cashflow: true, include_in_liquidity: payload.account_id !== "acc_card", include_in_net_worth: true, opened_at: "2022-03-01", closed_at: null, masked_reference: payload.account_id === "acc_card" ? "•••• 9012" : "•••• 4821", latest_balance: payload.account_id === "acc_card" ? "-2480.00" : "6420.00", available_balance: payload.account_id === "acc_card" ? null : "6180.00", balance_date: payload.account_id === "acc_card" ? "2026-05-31" : "2026-07-20", balance_source: "IMPORT_SOURCE", reconciliation_status: payload.account_id === "acc_card" ? "REVIEW_REQUIRED" : "MATCHED", freshness: payload.account_id === "acc_card" ? "STALE" : "CURRENT" }, balance_history: payload.account_id === "acc_card" ? [{ snapshot_id: "bal_card", balance_date: "2026-05-31", booked_balance: "-2480.00", currency: "EUR", source: "IMPORT_SOURCE" }] : [{ snapshot_id: "bal_02", balance_date: "2026-07-20", booked_balance: "6420.00", currency: "EUR", source: "IMPORT_SOURCE" }, { snapshot_id: "bal_01", balance_date: "2026-07-01", booked_balance: "5200.00", currency: "EUR", source: "RECONCILED" }], reconciliation: payload.account_id === "acc_card" ? { status: "REVIEW_REQUIRED", calculated_balance: "-2437.20", reported_balance: "-2480.00", balance_difference: "-42.80" } : { status: "MATCHED", calculated_balance: "6420.00", reported_balance: "6420.00", balance_difference: "0.00" } }),
    GetAccountBalanceHistory: envelope({ account_id: String(payload.account_id ?? "acc_main"), snapshots: [{ snapshot_id: "bal_02", balance_date: "2026-07-20", booked_balance: "6420.00", currency: "EUR", source: "IMPORT_SOURCE" }] }),
    GetBalanceReconciliation: envelope({ account_id: String(payload.account_id ?? "acc_main"), status: "MATCHED", calculated_balance: "6420.00", reported_balance: "6420.00", balance_difference: "0.00" }),
    GetLiquidityOverview: envelope({ valuation_currency: "EUR", as_of: "2026-07-20", liquid_funds: "18420.00", accounts: [], stale_account_ids: [], currency_conflicts: [] }),
    GetNetWorthOverview: envelope({ valuation_currency: "EUR", as_of: "2026-07-20", liquid_funds: "18420.00", savings: "12000.00", investments: "72500.00", other_assets: "0.00", total_assets: "90920.00", liabilities: "4500.00", net_worth: "86420.00", investable_assets: "84500.00", currency_conflicts: [], source_snapshot_ids: ["bal_01", "bal_02", "bal_03", "bal_04"] }),
    GetNetWorthHistory: envelope({ history: [{ as_of: "2026-05-31", net_worth: "82100.00" }, { as_of: "2026-06-30", net_worth: "84280.00" }, { as_of: "2026-07-20", net_worth: "86420.00" }] }),
    GetLiabilityOverview: envelope({ valuation_currency: "EUR", total_liabilities: "4500.00", liabilities: [{ item_id: "acc_card", display_name: "Kreditkarte", item_type: "CREDIT_CARD", amount: "2480.00", currency: "EUR", valuation_date: "2026-05-31" }, { item_id: "lia_loan", display_name: "Privatkredit", item_type: "LOAN", amount: "2020.00", currency: "EUR", valuation_date: "2026-07-20" }], currency_conflicts: [] }),
    GetAssetAllocation: envelope({ valuation_currency: "EUR", total_assets: "90920.00", allocation: { LIQUIDITY: "18420.00", INVESTMENTS: "72500.00", OTHER_ASSETS: "0.00" }, currency_conflicts: [] }),
    GetProjectedMonthEndBalance: envelope({ month, status: "READY", latest_confirmed_liquid_balance: "18420.00", realized_cashflow_since_snapshots: "0.00", remaining_expected_income: "320.00", remaining_expected_expenses: "603.40", projected_month_end_balance: "18136.60", snapshot_dates: ["2026-07-18", "2026-07-20"], source_event_sequence: 892 }),
    ListAccountReviews: envelope({ reviews: [
      { review_type: "BALANCE_DIFFERENCE", account_id: "acc_card", display_name: "Kreditkarte", reconciliation: { balance_difference: "-42.80", currency: "EUR" } },
      { review_type: "STALE_BALANCE", account_id: "acc_card", display_name: "Kreditkarte", balance_date: "2026-05-31" },
      { review_type: "OPENING_BALANCE_MISSING", account_id: "acc_cash", display_name: "Bargeld" },
    ] }),
    ListTransactions: envelope({
      transactions: [
        { transaction_id: "txn_104", booking_date: "2026-07-18", amount: "-83.42", currency: "EUR", counterparty: "Markthalle Süd", description: "Lebensmittel", category_code: "FOOD_GROCERIES", duplicate_status: "NONE", transfer_status: "NONE", refund_status: "NONE", cashflow_relevant: true },
        { transaction_id: "txn_103", booking_date: "2026-07-16", amount: "-49.00", currency: "EUR", counterparty: "Stadtwerke Mobil", description: "Monatskarte", category_code: "MOBILITY_PUBLIC_TRANSPORT", duplicate_status: "NONE", transfer_status: "NONE", refund_status: "NONE", cashflow_relevant: true },
        { transaction_id: "txn_102", booking_date: "2026-07-15", amount: "320.00", currency: "EUR", counterparty: "Nebentätigkeit", description: "Honorar", category_code: "INCOME_OTHER", duplicate_status: "NONE", transfer_status: "NONE", refund_status: "NONE", cashflow_relevant: true },
        { transaction_id: "txn_101", booking_date: "2026-07-03", amount: "-14.99", currency: "EUR", counterparty: "Stream AG", description: "Abo Juli", category_code: "SUBSCRIPTIONS", duplicate_status: "NONE", transfer_status: "NONE", refund_status: "NONE", cashflow_relevant: true },
        { transaction_id: "txn_100", booking_date: "2026-07-01", amount: "4000.00", currency: "EUR", counterparty: "Beispiel GmbH", description: "Gehalt", category_code: "INCOME_SALARY", duplicate_status: "NONE", transfer_status: "NONE", refund_status: "NONE", cashflow_relevant: true },
      ],
    }),
    GetTransactionDetails: envelope({
      transaction_id: String(payload.transaction_id ?? ""),
      booking_date: "2026-07-18",
      amount: "-83.42",
      currency: "EUR",
      counterparty: "Markthalle Süd",
      description: "Lebensmittel",
      category_code: "FOOD_GROCERIES",
      classification: { event_type: "TransactionClassificationConfirmed" },
      reconciliation: { duplicate_status: "NONE", transfer_status: "NONE", refund_status: "NONE", cashflow_relevant: true },
      event_history: [
        { sequence_number: 820, event_type: "TransactionNormalized", occurred_at: "2026-07-18T10:24:01Z" },
        { sequence_number: 828, event_type: "TransactionClassificationConfirmed", occurred_at: "2026-07-18T10:26:14Z" },
      ],
    }),
    GetCategoryBreakdown: envelope({
      period: month,
      categories: {
        HOUSING_RENT: { category_code: "HOUSING_RENT", gross_expense: "1180.00", refund_amount: "0", effective_expense: "1180.00", transaction_count: 1 },
        FOOD_GROCERIES: { category_code: "FOOD_GROCERIES", gross_expense: "412.80", refund_amount: "0", effective_expense: "412.80", transaction_count: 8 },
        MOBILITY_PUBLIC_TRANSPORT: { category_code: "MOBILITY_PUBLIC_TRANSPORT", gross_expense: "49.00", refund_amount: "0", effective_expense: "49.00", transaction_count: 1 },
        SUBSCRIPTIONS: { category_code: "SUBSCRIPTIONS", gross_expense: "47.96", refund_amount: "0", effective_expense: "47.96", transaction_count: 3 },
        UNCLASSIFIED: { category_code: "UNCLASSIFIED", gross_expense: "27.40", refund_amount: "0", effective_expense: "27.40", transaction_count: 2 },
      },
    }),
    ListClassificationReviews: envelope({ reviews: [
      { transaction_id: "txn_108", counterparty: "Café Morgen", amount: "-11.80", proposed_category: "FOOD_RESTAURANTS", confidence: "MEDIUM" },
      { transaction_id: "txn_109", counterparty: "Digital Services", amount: "-8.99", proposed_category: "SUBSCRIPTIONS", confidence: "LOW" },
    ] }),
    ListReconciliationReviews: envelope({ type: payload.type ?? "duplicates", reviews: [
      { relation_id: `rel_${String(payload.type ?? "duplicate")}_01`, title: "Mögliche Übereinstimmung", detail: "Betrag und Buchungsdatum liegen innerhalb der Policy-Toleranz.", confidence: "MEDIUM" },
    ] }),
    ListRecurringPatterns: envelope({ patterns: [
      { pattern_id: "pat_rent", merchant_key: "wohnraum eg", frequency: "MONTHLY", expected_amount: "1180.00", category_code: "HOUSING_RENT", account_id: "Giro", direction: "EXPENSE", amount_tolerance: "15.00", next_expected_date: "2026-08-01", expected_day_from: 1, expected_day_to: 3, status: "CONFIRMED", confidence: "HIGH", policy_version: "recurrence-v1" },
      { pattern_id: "pat_salary", merchant_key: "beispiel gmbh", frequency: "MONTHLY", expected_amount: "4000.00", category_code: "INCOME_SALARY", account_id: "Giro", direction: "INCOME", amount_tolerance: "50.00", next_expected_date: "2026-08-01", expected_day_from: 28, expected_day_to: 2, status: "CONFIRMED", confidence: "HIGH", policy_version: "recurrence-v1" },
      { pattern_id: "pat_stream", merchant_key: "stream ag", frequency: "MONTHLY", expected_amount: "14.99", category_code: "SUBSCRIPTIONS", account_id: "Giro", direction: "EXPENSE", amount_tolerance: "1.00", next_expected_date: "2026-08-03", expected_day_from: 2, expected_day_to: 5, status: "PROPOSED", confidence: "MEDIUM", policy_version: "recurrence-v1" },
    ] }),
    ListExpectedTransactions: envelope({ expected_transactions: [
      { expected_transaction_id: "exp_01", recurring_pattern_id: "pat_rent", merchant_key: "wohnraum eg", expected_date: "2026-08-01", expected_amount: "1180.00", amount_tolerance: "15.00", account_id: "Giro", category_code: "HOUSING_RENT", direction: "EXPENSE", status: "EXPECTED" },
      { expected_transaction_id: "exp_02", recurring_pattern_id: "pat_salary", merchant_key: "beispiel gmbh", expected_date: "2026-08-01", expected_amount: "4000.00", amount_tolerance: "50.00", account_id: "Giro", category_code: "INCOME_SALARY", direction: "INCOME", status: "MATCHED", matched_transaction_id: "txn_100", amount_deviation: "0", date_deviation: 0 },
      { expected_transaction_id: "exp_03", recurring_pattern_id: "pat_stream", merchant_key: "stream ag", expected_date: "2026-07-03", expected_amount: "14.99", amount_tolerance: "1.00", account_id: "Giro", category_code: "SUBSCRIPTIONS", direction: "EXPENSE", status: "MISSED" },
    ] }),
    GetForecast: envelope({ month, scenarios: {
      CONSERVATIVE: { forecast_id: "fc_31", scenario: "CONSERVATIVE", predicted_surplus: "1088.20", expected_income: "288.00", expected_fixed_expenses: "603.40", predicted_variable_expenses: "318.00", lower_bound: "1038.20", upper_bound: "1138.20", confidence: "MEDIUM", assumptions: ["Bestätigte aktive Muster", "Variable Ausgaben + 15 %"], source_event_sequence: 892, forecast_policy_version: "forecast-v1", status: "ACTIVE" },
      BASE: { forecast_id: "fc_32", scenario: "BASE", predicted_surplus: "1438.20", expected_income: "320.00", expected_fixed_expenses: "603.40", predicted_variable_expenses: "0.00", lower_bound: "1428.20", upper_bound: "1448.20", confidence: "MEDIUM", assumptions: ["Bestätigte aktive Muster", "Median historischer variabler Ausgaben"], source_event_sequence: 892, forecast_policy_version: "forecast-v1", status: "ACTIVE" },
      OPTIMISTIC: { forecast_id: "fc_33", scenario: "OPTIMISTIC", predicted_surplus: "1608.20", expected_income: "352.00", expected_fixed_expenses: "603.40", predicted_variable_expenses: "-138.00", lower_bound: "1598.20", upper_bound: "1618.20", confidence: "LOW", assumptions: ["Bestätigte aktive Muster", "Variable Ausgaben − 15 %"], source_event_sequence: 892, forecast_policy_version: "forecast-v1", status: "ACTIVE" },
    } }),
    ListForecastVersions: envelope({ month, versions: [
      { sequence_number: 892, event_type: "ForecastCreated", occurred_at: "2026-07-20T09:42:00Z", payload: { forecast_id: "fc_32", scenario: "BASE", predicted_surplus: "1438.20", status: "ACTIVE" } },
      { sequence_number: 861, event_type: "ForecastSuperseded", occurred_at: "2026-07-16T08:10:00Z", payload: { forecast_id: "fc_21", scenario: "BASE", predicted_surplus: "1284.00", status: "SUPERSEDED" } },
      { sequence_number: 804, event_type: "ForecastEvaluated", occurred_at: "2026-07-01T07:03:00Z", payload: { forecast_id: "fc_12", scenario: "BASE", predicted_surplus: "970.00", status: "EVALUATED" } },
    ] }),
    GetForecastEvaluation: envelope({ month, evaluations: [{
      forecast_id: "fc_12", actual_income: "3200.00", actual_expenses: "2350.00", actual_surplus: "850.00", absolute_error: "120.00", percentage_error: "14.12", expected_transactions_matched: 8, expected_transactions_missed: 1, unexpected_transactions: 2,
      component_accuracy: { recurring_income_matched: "3200.00", recurring_expenses_matched: "1490.00", predicted_variable_expenses: "780.00", actual_variable_expenses: "860.00", surplus_absolute_error: "120.00" },
    }] }),
    ListImportBatches: envelope({ imports: [
      { import_id: "imp_20260718", created_at: "2026-07-18T10:24:00Z", parser_version: "generic-v1", status: "IMPORTED", content_hash: "a421…9bf0" },
      { import_id: "imp_20260702", created_at: "2026-07-02T08:03:00Z", parser_version: "generic-v1", status: "IMPORTED", content_hash: "c038…7a12" },
    ] }),
    ListBackups: envelope({ backups: [
      { archive_id: "bkp_a73e3e8f2e4b4f9d84cb140f0a84cf41", path: "/Lokale Daten/finance-backups/finance-20260720.finance-backup", size: 168422, created_at: "2026-07-20T21:42:00Z", event_store_sequence: 892, verification_status: "VALID" },
      { archive_id: "bkp_49fddff733e4499a8f6844f0f8fd705e", path: "/Lokale Daten/finance-backups/finance-20260713.finance-backup", size: 163984, created_at: "2026-07-13T08:15:00Z", event_store_sequence: 841, verification_status: "VALID" },
    ] }),
    GetStoreIntegrity: envelope({ status: "VALID", checked_at: "2026-07-20T21:42:03Z", store_schema_version: 2, event_count: 892, last_event_sequence: 892, import_file_count: 6, storage_encryption: "FERNET_AUTHENTICATED" }),
    GetKeyStatus: envelope({ database_key: { strategy: "KeychainKeyProvider", status: "AVAILABLE", fingerprint: "7f4a8bc2e19dd431" }, archive_key: { strategy: "KeychainKeyProvider", status: "AVAILABLE", fingerprint: "b9a0c14e383fed80", independent_from_store: true } }),
    GetMigrationStatus: envelope({ current_store_schema_version: 3, supported_store_schema_version: 3, status: "CURRENT", history: [{ migration_id: "store_v2_to_v3", from_version: 2, to_version: 3, applied_at: "2026-07-20T21:40:00Z", application_version: "0.9.0" }], downgrade_protection: "ENABLED" }),
  };
  return responses[name] ?? envelope(null, "EMPTY");
}
